In [1]:
import numpy as np

# Method 1 : Use numpy ndarray

In [2]:
# Create a 2D array
A = np.array([[1, 2],[3, 4]])

print(A)

[[1 2]
 [3 4]]


In [3]:
# display the type of A
type(A)

numpy.ndarray

In [4]:
invA = np.linalg.inv(A)

print(invA)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [5]:
I = np.matmul(A, invA)

print(np.round(I))

[[1. 0.]
 [0. 1.]]


# Method 2 : use numpy maxtrix

In [6]:
# Create a 2D matrix
B = np.matrix([[1, 2],[3, 4]])

print(B)

[[1 2]
 [3 4]]


In [7]:
print(type(B))

<class 'numpy.matrix'>


In [8]:
invB = B**-1

print(invB)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [9]:
I = B * invB

print(np.round(I))

[[1. 0.]
 [0. 1.]]
