# Fine the inverse of a matrix

In [1]:
import numpy as np

In [2]:
A = np.matrix([[1, 1, 2], [1, 2, 1], [0, 1, 3]])



In [3]:
# Return the inverse matrix
invA = np.linalg.inv(A)

print(invA)

[[ 1.25 -0.25 -0.75]
 [-0.75  0.75  0.25]
 [ 0.25 -0.25  0.25]]
