In [1]:
import numpy as np


# numpy.linalg.eig
linalg.eig(a)[source]

Compute the eigenvalues and right eigenvectors of a square array.

**Parameters**

a(…, M, M) array

Matrices for which the eigenvalues and right eigenvectors will be computed

**Returns**

*w(…, M) array*

The eigenvalues, each repeated according to its multiplicity. The eigenvalues are not necessarily ordered. The resulting array will be of complex type, unless the imaginary part is zero in which case it will be cast to a real type. When a is real the resulting eigenvalues will be real (0 imaginary part) or occur in conjugate pairs

*v(…, M, M) array*

The normalized (unit “length”) eigenvectors, such that the column v[:,i] is the eigenvector corresponding to the eigenvalue w[i].

**Raises**
LinAlgError

If the eigenvalue computation does not converge.

In [6]:
A = [[0, 1, -1], [-6, -11, 6], [-6, -11, 5]]

In [7]:

w, v = np.linalg.eig(A)

print("Eigenvalue = ")
print(w)

print("Eigenvector = ")
print(v)

Eigenvalue = 
[-1. -2. -3.]
Eigenvector = 
[[ 7.07106781e-01 -2.18217890e-01 -9.20574618e-02]
 [ 5.05857283e-15 -4.36435780e-01 -5.52344771e-01]
 [ 7.07106781e-01 -8.72871561e-01 -8.28517156e-01]]
